Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace MedicaTeams.Controllers
{
    [Authorize(Roles = "Administrator,Volunteer")]
    public class DashboardController:Controller
    {
        public IActionResult Dashboard()
        {
            return View();
        }
    }
}

Controllers/VaccineCandidatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MedicaTeams.Data;
using MedicaTeams.Models;
using Microsoft.AspNetCore.Authorization;

namespace MedicaTeams.Controllers
{
    [Authorize(Roles = "Administrator,Volunteer")]
    public class VaccineCandidatesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VaccineCandidatesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: VaccineCandidates
        public async Task<IActionResult> Index(string searchstring,string sortOrder, int? pageNumber, string currentFilter)
        {
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            if (searchstring != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchstring = currentFilter;
            }
            ViewData["CurrentFilter"] = searchstring;
            var vaccinecandidates = from v in _context.VaccineCandidate.Include(v => v.Venue)
                                    select v;
            if (!String.IsNullOrEmpty(searchstring))
            {
                vaccinecandidates = vaccinecandidates.Where(s => s.Name.Contains(searchstring));
            }
            switch (sortOrder)
            {
               
                case "Date":
                    vaccinecandidates = vaccinecandidates.OrderBy(s => s.VaccineDate);
                    break;
                case "date_desc":
                    vaccinecandidates = vaccinecandidates.OrderByDescending(s => s.VaccineDate);
                    break;
                default:
                    vaccinecandidates = vaccinecandidates.OrderBy(s => s.Name);
                    break;
            }
            int pageSize = 5;
            return View(await PaginatedList<VaccineCandidate>.CreateAsync(vaccinecandidates.AsNoTracking(), pageNumber ?? 1, pageSize));
            //var applicationDbContext = _context.VaccineCandidate.Include(v => v.Venue);
            return View(await vaccinecandidates.ToListAsync());
        }

        // GET: VaccineCandidates/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vaccineCandidate = await _context.VaccineCandidate
                .Include(v => v.Venue)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vaccineCandidate == null)
            {
                return NotFound();
            }

            return View(vaccineCandidate);
        }

        // GET: VaccineCandidates/Create
        public IActionResult Create()
        {
            ViewData["VenueId"] = new SelectList(_context.Venue, "VenueId", "VenueId");
            ViewBag.Options = new SelectList(_context.Venue, nameof(Venue.VenueId), nameof(Venue.VenueName));
            return View();
        }

        // POST: VaccineCandidates/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Age,PhoneNumber,VaccineDate,Abnormalities,VenueId")] VaccineCandidate vaccineCandidate)
        {
            if (ModelState.IsValid)
            {
                _context.Add(vaccineCandidate);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["VenueId"] = new SelectList(_context.Venue, "VenueId", "VenueId", vaccineCandidate.VenueId);
            return View(vaccineCandidate);
        }

        // GET: VaccineCandidates/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vaccineCandidate = await _context.VaccineCandidate.FindAsync(id);
            if (vaccineCandidate == null)
            {
                return NotFound();
            }
            ViewData["VenueId"] = new SelectList(_context.Venue, "VenueId", "VenueId", vaccineCandidate.VenueId);
            ViewBag.Options = new SelectList(_context.Venue, nameof(Venue.VenueId), nameof(Venue.VenueName));
            return View(vaccineCandidate);
        }

        // POST: VaccineCandidates/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Age,PhoneNumber,VaccineDate,Abnormalities,VenueId")] VaccineCandidate vaccineCandidate)
        {
            if (id != vaccineCandidate.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vaccineCandidate);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VaccineCandidateExists(vaccineCandidate.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["VenueId"] = new SelectList(_context.Venue, "VenueId", "VenueId", vaccineCandidate.VenueId);
            return View(vaccineCandidate);
        }

        // GET: VaccineCandidates/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vaccineCandidate = await _context.VaccineCandidate
                .Include(v => v.Venue)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vaccineCandidate == null)
            {
                return NotFound();
            }

            return View(vaccineCandidate);
        }

        // POST: VaccineCandidates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var vaccineCandidate = await _context.VaccineCandidate.FindAsync(id);
            _context.VaccineCandidate.Remove(vaccineCandidate);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VaccineCandidateExists(int id)
        {
            return _context.VaccineCandidate.Any(e => e.Id == id);
        }
    }
}

Controllers/VenuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MedicaTeams.Data;
using MedicaTeams.Models;
using Microsoft.AspNetCore.Authorization;

namespace MedicaTeams.Controllers
{
    public class VenuesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VenuesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Venues
        public async Task<IActionResult> Index(string searchstring)
        {
            var venues = from v in _context.Venue
                         select v;
            if(!String.IsNullOrEmpty(searchstring))
            {
                venues = venues.Where(s => s.DistrictName.Contains(searchstring));
            }
            return View(await venues.ToListAsync());
        }
        public async Task<IActionResult> Vaccinesearch(string searchstring)
        {
            var venues = from v in _context.Venue
                         select v;
            if (!String.IsNullOrEmpty(searchstring))
            {
                venues = venues.Where(s => s.VaccineName.Contains(searchstring));
            }
            return View(await venues.ToListAsync());
        }
        [Authorize(Roles = "Administrator")]
        // GET: Venues/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venue = await _context.Venue
                .FirstOrDefaultAsync(m => m.VenueId == id);
            if (venue == null)
            {
                return NotFound();
            }

            return View(venue);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Venues/Create
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Administrator")]
        // POST: Venues/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VenueId,VenueName,DistrictName,VaccineName,VaccineAmount,StartDate,VolunteerGroup,NumberOfVolunteer")] Venue venue)
        {
            if (ModelState.IsValid)
            {
                _context.Add(venue);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(venue);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Venues/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venue = await _context.Venue.FindAsync(id);
            if (venue == null)
            {
                return NotFound();
            }
            return View(venue);
        }
        [Authorize(Roles = "Administrator")]
        // POST: Venues/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VenueId,VenueName,DistrictName,VaccineName,VaccineAmount,StartDate,VolunteerGroup,NumberOfVolunteer")] Venue venue)
        {
            if (id != venue.VenueId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(venue);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VenueExists(venue.VenueId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(venue);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Venues/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venue = await _context.Venue
                .FirstOrDefaultAsync(m => m.VenueId == id);
            if (venue == null)
            {
                return NotFound();
            }

            return View(venue);
        }
        [Authorize(Roles = "Administrator")]
        // POST: Venues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var venue = await _context.Venue.FindAsync(id);
            _context.Venue.Remove(venue);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VenueExists(int id)
        {
            return _context.Venue.Any(e => e.VenueId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title class="footer-logo">@ViewData["Title"] MedicaTeams</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MedicaTeams</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Pricing">Pricing</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Volunteers" asp-action="Create">Be A Volunteer</a>
                        </li>
                        @*@if (SignInManager.IsSignedIn(User))
        {
            if (User.IsInRole("Administrator"))
            {
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Venues" asp-action="Index">Venues</a>
                </li>
            }

        }
        @if (SignInManager.IsSignedIn(User))
        {
            if (User.IsInRole("Administrator"))
            {
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="VaccineCandidates" asp-action="Index">Vaccines</a>
                </li>
            }
        }*@
                        @if (SignInManager.IsSignedIn(User))
                        {


                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Dashboard">Dashboard</a>
                            </li>

                        }
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="container border-top footer-section py-2">
        <div class="row">
            <div class="col-12 col-md">
                <p class="footer-logo">MedicaTeams</p>
                <small class="d-block mb-3 text-muted">© 2021-2022 By Safayet Jamil</small>
            </div>
            <div class="col-6 col-md">
                <h5>Features</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Searching</a></li>
                    <li><a class="text-muted" href="#">Sorting</a></li>
                    <li><a class="text-muted" href="#">Pagination</a></li>
                    <li><a class="text-muted" href="#">Authentication</a></li>
                    <li><a class="text-muted" href="#">Role Authorization</a></li>
                    <li><a class="text-muted" href="#">access Control</a></li>

                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Languages</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">C sharp</a></li>
                    <li><a class="text-muted" href="#">Asp net core </a></li>
                    <li><a class="text-muted" href="#">SQL</a></li>

                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Our Team</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Md:Shalauddin Kabir (Project cordinator)</a></li>
                    <li><a class="text-muted" href="#">Sheikh Mekail(082)</a></li>
                    <li><a class="text-muted" href="#">Kazi Safayet Jamil(062)</a></li>
                    
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Social Media</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Facebook</a></li>
                    <li><a class="text-muted" href="#">Instagram</a></li>
                    <li><a class="text-muted" href="#">Twitter</a></li>
                    <li><a class="text-muted" href="#">Linkedin</a></li>
                </ul>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>