Controllers/ApplyOnlinesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MedicaTeams.Data;
using MedicaTeams.Models;

namespace MedicaTeams.Controllers
{
    public class ApplyOnlinesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ApplyOnlinesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: ApplyOnlines
        public async Task<IActionResult> Index(string searchString, string sortOrder, int? pageNumber, string currentFilter)
        {
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;
            var onlines = from o in _context.ApplyOnlines.Include(a => a.Venue)
                          select o;
            if(!String.IsNullOrEmpty(searchString))
            {
                onlines = onlines.Where(s=>s.Name.Contains(searchString));
            }
            switch (sortOrder)
            {

                case "Date":
                    onlines = onlines.OrderBy(s => s.PreferedDate);
                    break;
                case "date_desc":
                    onlines = onlines.OrderByDescending(s => s.PreferedDate);
                    break;
                default:
                    onlines = onlines.OrderBy(s => s.Name);
                    break;
            }
            int pageSize = 5;
            return View(await PaginatedList<ApplyOnline>.CreateAsync(onlines.AsNoTracking(), pageNumber ?? 1, pageSize));
            //var applicationDbContext = _context.ApplyOnlines.Include(a => a.Venue);
            return View(await onlines.ToListAsync());
        }

        // GET: ApplyOnlines/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applyOnline = await _context.ApplyOnlines
                .Include(a => a.Venue)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (applyOnline == null)
            {
                return NotFound();
            }

            return View(applyOnline);
        }

        // GET: ApplyOnlines/Create
        public IActionResult Create()
        {
            ViewData["VenueId"] = new SelectList(_context.Venue, "VenueId", "VenueId");
            ViewBag.Options = new SelectList(_context.Venue, nameof(Venue.VenueId), nameof(Venue.VenueName));
            return View();
        }

        // POST: ApplyOnlines/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,PhoneNumber,Age,PreferedDate,VenueId,Abnormalities")] ApplyOnline applyOnline)
        {
            if (ModelState.IsValid)
            {
                _context.Add(applyOnline);
                await _context.SaveChangesAsync();
                return RedirectToAction("Welcome","Home");
            }
            
            ViewData["VenueId"] = new SelectList(_context.Venue, "VenueId", "VenueId", applyOnline.VenueId);
            return RedirectToAction(nameof(applyOnline));
        }

        // GET: ApplyOnlines/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applyOnline = await _context.ApplyOnlines.FindAsync(id);
            if (applyOnline == null)
            {
                return NotFound();
            }
            ViewData["VenueId"] = new SelectList(_context.Venue, "VenueId", "VenueId", applyOnline.VenueId);
            ViewBag.Options = new SelectList(_context.Venue, nameof(Venue.VenueId), nameof(Venue.VenueName));
            return View(applyOnline);
        }

        // POST: ApplyOnlines/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,PhoneNumber,Age,PreferedDate,VenueId,Abnormalities")] ApplyOnline applyOnline)
        {
            if (id != applyOnline.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(applyOnline);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApplyOnlineExists(applyOnline.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["VenueId"] = new SelectList(_context.Venue, "VenueId", "VenueId", applyOnline.VenueId);
            
            
            return View(applyOnline);
        }

        // GET: ApplyOnlines/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applyOnline = await _context.ApplyOnlines
                .Include(a => a.Venue)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (applyOnline == null)
            {
                return NotFound();
            }

            return View(applyOnline);
        }

        // POST: ApplyOnlines/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var applyOnline = await _context.ApplyOnlines.FindAsync(id);
            _context.ApplyOnlines.Remove(applyOnline);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ApplyOnlineExists(int id)
        {
            return _context.ApplyOnlines.Any(e => e.Id == id);
        }
    }
}

Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;

namespace MedicaTeams.Controllers
{
    [Authorize(Roles = "Administrator,Volunteer")]
    public class DashboardController:Controller
    {
        public IActionResult Dashboard()
        {
            return View();
        }
    }
}

Controllers/VenuesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MedicaTeams.Data;
using MedicaTeams.Models;
using Microsoft.AspNetCore.Authorization;

namespace MedicaTeams.Controllers
{
    public class VenuesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VenuesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Venues
        public async Task<IActionResult> Index(string searchstring)
        {
            var venues = from v in _context.Venue
                         select v;
            if(!String.IsNullOrEmpty(searchstring))
            {
                venues = venues.Where(s => s.DistrictName.Contains(searchstring));
            }
            return View(await venues.ToListAsync());
        }
        public async Task<IActionResult> Vaccinesearch(string searchstring)
        {
            var venues = from v in _context.Venue
                         select v;
            if (!String.IsNullOrEmpty(searchstring))
            {
                venues = venues.Where(s => s.VaccineName.Contains(searchstring));
            }
            return View(await venues.ToListAsync());
        }
        [Authorize(Roles = "Administrator")]
        // GET: Venues/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venue = await _context.Venue
                .FirstOrDefaultAsync(m => m.VenueId == id);
            if (venue == null)
            {
                return NotFound();
            }

            return View(venue);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Venues/Create
        public IActionResult Create()
        {
            return View();
        }
        [Authorize(Roles = "Administrator")]
        // POST: Venues/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VenueId,VenueName,DistrictName,VaccineName,VaccineAmount,StartDate,VolunteerGroup,NumberOfVolunteer")] Venue venue)
        {
            if (ModelState.IsValid)
            {
                _context.Add(venue);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(venue);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Venues/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venue = await _context.Venue.FindAsync(id);
            if (venue == null)
            {
                return NotFound();
            }
            return View(venue);
        }
        [Authorize(Roles = "Administrator")]
        // POST: Venues/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("VenueId,VenueName,DistrictName,VaccineName,VaccineAmount,StartDate,VolunteerGroup,NumberOfVolunteer")] Venue venue)
        {
            if (id != venue.VenueId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(venue);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VenueExists(venue.VenueId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(venue);
        }
        [Authorize(Roles = "Administrator")]
        // GET: Venues/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var venue = await _context.Venue
                .FirstOrDefaultAsync(m => m.VenueId == id);
            if (venue == null)
            {
                return NotFound();
            }

            return View(venue);
        }
        [Authorize(Roles = "Administrator")]
        // POST: Venues/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var venue = await _context.Venue.FindAsync(id);
            _context.Venue.Remove(venue);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VenueExists(int id)
        {
            return _context.Venue.Any(e => e.VenueId == id);
        }
    }
}

Views/Dashboard/Dashboard.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<div class="container space">
    <div class="row">

        <div class="col-sm">
            <div class="card border-primary mb-3" style="max-width: 18rem;">
                <div class="card-header">List</div>
                <div class="card-body">
                    <a asp-controller="Venues" asp-action="Index" class="card-title text-dark dashboard-text">Venue Index</a>
                    <p class="card-text">By clicking venue index it will take you to the list of total venues and allows you searching</p>
                </div>
            </div>
        </div>
        <div class="col-sm">
            <div class="card  border-primary mb-3" style="max-width: 18rem;">
                <div class="card-header">List</div>
                <div class="card-body">
                    <a asp-controller="VaccineCandidates" asp-action="Index" class="card-title text-dark dashboard-text">Candidates Index</a>
                    <p class="card-text">By clicking cadidates index it will take you to the list of total candidates and allows you sorting</p>
                </div>
            </div>
        </div>
        <div class="col-sm">
            <div class="card border-info mb-3" style="max-width: 18rem;">
                <div class="card-header">Add</div>
                <div class="card-body">
                    <a asp-controller="VaccineCandidates" asp-action="Create" class="card-title text-dark dashboard-text">Venue Candidate</a>
                    <p class="card-text">By clicking add it will take you to a form where you can add single candidates who comes to venue</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-sm">
            <div class="card border-info mb-3" style="max-width: 18rem;">
                <div class="card-header">List</div>
                <div class="card-body">
                    <a asp-controller="ApplyOnlines" asp-action="Index" class="card-title text-dark dashboard-text">Online Applicants</a>
                    <p class="card-text">By clicking online index it will take you to the list of total list of online applicants and other actions.</p>
                </div>
            </div>
        </div>
        @if (SignInManager.IsSignedIn(User))
        {
            if (User.IsInRole("Administrator"))
            {
                <div class="col-sm">
                    <div class="card  border-info mb-3" style="max-width: 18rem;">
                        <div class="card-header">Add</div>
                        <div class="card-body">
                            <a asp-controller="Venues" asp-action="Create" class="card-title text-dark dashboard-text">Add Venue</a>
                            <p class="card-text">By clicking Add venue it will take you to a to a form where you can add venues for your events data.</p>
                        </div>
                    </div>
                </div>
                <div class="col-sm">
                    <div class="card border-primary mb-3" style="max-width: 18rem;">
                        <div class="card-header">Add</div>
                        <div class="card-body">
                            <a class="card-title text-dark dashboard-text" asp-area="Identity" asp-page="/Account/Register">Add Volunteer</a>
                            <p class="card-text">By clicking venue index it will take you to a form where you can add volunteer for your event.</p>
                        </div>
                    </div>
                </div>
            }
        }

    </div>
    <div class="row">
        @if (SignInManager.IsSignedIn(User))
        {
            if (User.IsInRole("Administrator"))
            {
                <div class="col-sm">
                    <div class="card border-primary mb-3" style="max-width: 18rem;">
                        <div class="card-header">Add</div>
                        <div class="card-body">
                            <a class="card-title text-dark dashboard-text" asp-area="" asp-controller="Volunteers" asp-action="Index">Volunteer List</a>
                            <p class="card-text">By clicking volunteers index it will take you to the list of total volunteers and allows you sorting</p>
                        </div>
                    </div>
                </div>
            }
        }
            </div>
</div>




    
   